language: java
jdk:
  - oraclejdk8
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
before_script:
  - cp ./src/test/resources/database.travisci.properties ./src/test/resources/database.properties